In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
pd.set_option('display.max_columns', None)

In [253]:
dfc = pd.read_csv('Chicago raw data april to june 2020.csv')

In [261]:
dfc.head()

,Trip ID,Taxi ID,Trip Start Timestamp,Trip End Timestamp,Trip Seconds,Trip Miles,Pickup Census Tract,Dropoff Census Tract,Pickup Community Area,Dropoff Community Area,Fare,Tips,Tolls,Extras,Trip Total,Payment Type,Company,Pickup Centroid Latitude,Pickup Centroid Longitude,Pickup Centroid Location,Dropoff Centroid Latitude,Dropoff Centroid Longitude,Dropoff Centroid Location
0,ec5f9c807dad532712773a08993ae651f31e42c4,c4c7fd9594d514cfea1eded04c92e0b708fbc141d2ca3a...,2020-04-01,4/1/2020 0:15,321.0,0.84,NaN,NaN,8.0,8.0,5.50,0.0,0.0,0.0,5.50,Cash,Chicago Carriage Cab Corp,41.899602,-87.633308,POINT (-87.6333080367 41.899602111),41.899602,-87.633308,POINT (-87.6333080367 41.899602111)
1,90701f1b3ca683ddb13a7741576bc4acde417535,ca4914e7e91e8c3d5c5c6204967fa2cf4dc39591a49ef1...,2020-04-01,4/1/2020 0:15,960.0,0.40,NaN,NaN,28.0,41.0,19.25,0.0,0.0,0.0,19.25,Unknown,Taxi Affiliation Services,41.874005,-87.663518,POINT (-87.6635175498 41.874005383),41.794090,-87.592311,POINT (-87.592310855 41.794090253)
2,74beabaf45f1cde01eb791ae47aa546a2a4b1e16,8c996b78641f57de21b068fa17d4224cd9f1da237ccd78...,2020-04-01,4/1/2020 0:00,0.0,0.00,NaN,NaN,31.0,31.0,3.25,0.0,0.0,0.0,3.25,Cash,Taxi Affiliation Services,41.850266,-87.667569,POINT (-87.667569312 41.8502663663),41.850266,-87.667569,POINT (-87.667569312 41.8502663663)
3,8a75a64181ddeaab259e2142edaf0ca7dc97cace,70bf7d4596f2cb1e28077895f272ce60c503eeeaa98208...,2020-04-01,4/1/2020 0:15,280.0,0.77,NaN,NaN,2.0,2.0,5.00,0.0,0.0,0.0,5.00,Cash,Flash Cab,42.001571,-87.695013,POINT (-87.6950125892 42.001571027),42.001571,-87.695013,POINT (-87.6950125892 42.001571027)
4,c97c57c68c31b889b0112c83e67c814c4af1a9c8,799fa15fea677c82e123d9033946ee5c9dbf5b33d0d2b0...,2020-04-01,4/1/2020 0:00,NaN,0.00,NaN,NaN,32.0,32.0,NaN,NaN,NaN,NaN,NaN,Cash,Chicago Carriage Cab Corp,41.878866,-87.625192,POINT (-87.6251921424 41.8788655841),41.878866,-87.625192,POINT (-87.6251921424 41.8788655841)

In [255]:
dfc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 225917 entries, 0 to 225916
Data columns (total 23 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Trip ID                     225917 non-null  object
 1   Taxi ID                     225906 non-null  object
 2   Trip Start Timestamp        225917 non-null  object
 3   Trip End Timestamp          225734 non-null  object
 4   Trip Seconds                225595 non-null  float64
 5   Trip Miles                  225916 non-null  float64
 6   Pickup Census Tract         6659 non-null    float64
 7   Dropoff Census Tract        6180 non-null    float64
 8   Pickup Community Area       208908 non-null  float64
 9   Dropoff Community Area      203401 non-null  float64
 10  Fare                        225906 non-null  float64
 11  Tips                        225906 non-null  float64
 12  Tolls                       225906 non-null  float64
 13  Extras                      225906 non-null  float64
 14  Trip Total                  225906 non-null  float64
 15  Payment Type                225917 non-null  object
 16  Company                     225917 non-null  object
 17  Pickup Centroid Latitude    208920 non-null  float64
 18  Pickup Centroid Longitude   208920 non-null  float64
 19  Pickup Centroid Location    208920 non-null  object
 20  Dropoff Centroid Latitude   203436 non-null  float64
 21  Dropoff Centroid Longitude  203436 non-null  float64
 22  Dropoff Centroid  Location  203436 non-null  object
dtypes: float64(15), object(8)
memory usage: 39.6+ MB

In [256]:
dfc.dropna(subset = ['Trip End Timestamp'], inplace = True)
# Drop null end times as it causes problems during conversion to datetime datatype

Tasks:
1. Need to change timestamp fields from object to datetime
2. Adding date time columns such as day of month, year, month, day of week

In [260]:
dfc['Trip Start Timestamp'] = pd.to_datetime(dfc['Trip Start Timestamp'])
                                             #, format="%m/%d/%Y %I:%M:%S %p")

In [263]:
dfc['Trip End Timestamp'] = pd.to_datetime(dfc['Trip End Timestamp'])
                                           #, format="%m/%d/%Y %I:%M:%S %p")

In [264]:
dfc.rename(columns={'Trip Start Timestamp':'TripStart','Trip End Timestamp':'TripEnd'}, inplace = True)

In [265]:
dfc.drop(['Trip ID','Taxi ID'], axis = 1, inplace = True)
dfc.rename(columns={'Trip Start Timestamp':'TripStart','Trip End Timestamp':'TripEnd'}, inplace = True)

In [266]:
dfc.head()

,TripStart,TripEnd,Trip Seconds,Trip Miles,Pickup Census Tract,Dropoff Census Tract,Pickup Community Area,Dropoff Community Area,Fare,Tips,Tolls,Extras,Trip Total,Payment Type,Company,Pickup Centroid Latitude,Pickup Centroid Longitude,Pickup Centroid Location,Dropoff Centroid Latitude,Dropoff Centroid Longitude,Dropoff Centroid Location
0,2020-04-01,2020-04-01 00:15:00,321.0,0.84,NaN,NaN,8.0,8.0,5.50,0.0,0.0,0.0,5.50,Cash,Chicago Carriage Cab Corp,41.899602,-87.633308,POINT (-87.6333080367 41.899602111),41.899602,-87.633308,POINT (-87.6333080367 41.899602111)
1,2020-04-01,2020-04-01 00:15:00,960.0,0.40,NaN,NaN,28.0,41.0,19.25,0.0,0.0,0.0,19.25,Unknown,Taxi Affiliation Services,41.874005,-87.663518,POINT (-87.6635175498 41.874005383),41.794090,-87.592311,POINT (-87.592310855 41.794090253)
2,2020-04-01,2020-04-01 00:00:00,0.0,0.00,NaN,NaN,31.0,31.0,3.25,0.0,0.0,0.0,3.25,Cash,Taxi Affiliation Services,41.850266,-87.667569,POINT (-87.667569312 41.8502663663),41.850266,-87.667569,POINT (-87.667569312 41.8502663663)
3,2020-04-01,2020-04-01 00:15:00,280.0,0.77,NaN,NaN,2.0,2.0,5.00,0.0,0.0,0.0,5.00,Cash,Flash Cab,42.001571,-87.695013,POINT (-87.6950125892 42.001571027),42.001571,-87.695013,POINT (-87.6950125892 42.001571027)
4,2020-04-01,2020-04-01 00:00:00,NaN,0.00,NaN,NaN,32.0,32.0,NaN,NaN,NaN,NaN,NaN,Cash,Chicago Carriage Cab Corp,41.878866,-87.625192,POINT (-87.6251921424 41.8788655841),41.878866,-87.625192,POINT (-87.6251921424 41.8788655841)

In [267]:
type(dfc['TripStart'])

pandas.core.series.Series

In [268]:
dateFeats = ['TripStart','TripEnd']

In [269]:
for feat in dateFeats:
    dfc[feat+'_dayofmonth'] = dfc[feat].dt.day
    dfc[feat+'_month'] = dfc[feat].dt.month
    dfc[feat+'_year'] = dfc[feat].dt.year
    dfc[feat+'_dayofweek'] = dfc[feat].dt.dayofweek
    dfc[feat+'_week'] = dfc[feat].dt.week
    dfc[feat+'_time'] = dfc[feat].dt.time
    dfc[feat+'_hourofday'] = dfc[feat].dt.hour
    dfc[feat+'_minuteofday'] = dfc[feat].dt.minute

In [270]:
dfc.head(50)

,TripStart,TripEnd,Trip Seconds,Trip Miles,Pickup Census Tract,Dropoff Census Tract,Pickup Community Area,Dropoff Community Area,Fare,Tips,Tolls,Extras,Trip Total,Payment Type,Company,Pickup Centroid Latitude,Pickup Centroid Longitude,Pickup Centroid Location,Dropoff Centroid Latitude,Dropoff Centroid Longitude,Dropoff Centroid Location,TripStart_dayofmonth,TripStart_month,TripStart_year,TripStart_dayofweek,TripStart_week,TripStart_time,TripStart_hourofday,TripStart_minuteofday,TripEnd_dayofmonth,TripEnd_month,TripEnd_year,TripEnd_dayofweek,TripEnd_week,TripEnd_time,TripEnd_hourofday,TripEnd_minuteofday
0,2020-04-01 00:00:00,2020-04-01 00:15:00,321.0,0.84,NaN,NaN,8.0,8.0,5.50,0.00,0.0,0.0,5.50,Cash,Chicago Carriage Cab Corp,41.899602,-87.633308,POINT (-87.6333080367 41.899602111),41.899602,-87.633308,POINT (-87.6333080367 41.899602111),1,4,2020,2,14,00:00:00,0,0,1,4,2020,2,14,00:15:00,0,15
1,2020-04-01 00:00:00,2020-04-01 00:15:00,960.0,0.40,NaN,NaN,28.0,41.0,19.25,0.00,0.0,0.0,19.25,Unknown,Taxi Affiliation Services,41.874005,-87.663518,POINT (-87.6635175498 41.874005383),41.794090,-87.592311,POINT (-87.592310855 41.794090253),1,4,2020,2,14,00:00:00,0,0,1,4,2020,2,14,00:15:00,0,15
2,2020-04-01 00:00:00,2020-04-01 00:00:00,0.0,0.00,NaN,NaN,31.0,31.0,3.25,0.00,0.0,0.0,3.25,Cash,Taxi Affiliation Services,41.850266,-87.667569,POINT (-87.667569312 41.8502663663),41.850266,-87.667569,POINT (-87.667569312 41.8502663663),1,4,2020,2,14,00:00:00,0,0,1,4,2020,2,14,00:00:00,0,0
3,2020-04-01 00:00:00,2020-04-01 00:15:00,280.0,0.77,NaN,NaN,2.0,2.0,5.00,0.00,0.0,0.0,5.00,Cash,Flash Cab,42.001571,-87.695013,POINT (-87.6950125892 42.001571027),42.001571,-87.695013,POINT (-87.6950125892 42.001571027),1,4,2020,2,14,00:00:00,0,0,1,4,2020,2,14,00:15:00,0,15
4,2020-04-01 00:00:00,2020-04-01 00:00:00,NaN,0.00,NaN,NaN,32.0,32.0,NaN,NaN,NaN,NaN,NaN,Cash,Chicago Carriage Cab Corp,41.878866,-87.625192,POINT (-87.6251921424 41.8788655841),41.878866,-87.625192,POINT (-87.6251921424 41.8788655841),1,4,2020,2,14,00:00:00,0,0,1,4,2020,2,14,00:00:00,0,0
5,2020-04-01 00:00:00,2020-04-01 00:30:00,2400.0,6.60,NaN,NaN,77.0,77.0,25.00,0.00,0.0,0.0,25.00,Cash,Taxi Affiliation Services,41.986712,-87.663416,POINT (-87.6634164054 41.9867117999),41.986712,-87.663416,POINT (-87.6634164054 41.9867117999),1,4,2020,2,14,00:00:00,0,0,1,4,2020,2,14,00:30:00,0,30
6,2020-04-01 00:00:00,2020-04-01 00:00:00,7.0,0.00,NaN,NaN,32.0,32.0,3.25,0.00,0.0,0.0,3.25,Cash,Chicago Carriage Cab Corp,41.878866,-87.625192,POINT (-87.6251921424 41.8788655841),41.878866,-87.625192,POINT (-87.6251921424 41.8788655841),1,4,2020,2,14,00:00:00,0,0,1,4,2020,2,14,00:00:00,0,0
7,2020-04-01 00:00:00,2020-04-01 00:15:00,1620.0,13.50,NaN,NaN,NaN,NaN,34.75,0.00,0.0,4.0,38.75,Cash,Star North Management LLC,NaN,NaN,NaN,NaN,NaN,NaN,1,4,2020,2,14,00:00:00,0,0,1,4,2020,2,14,00:15:00,0,15
8,2020-04-01 00:15:00,2020-04-01 00:15:00,300.0,1.00,NaN,NaN,28.0,32.0,6.00,0.00,0.0,0.0,6.00,Cash,Taxi Affiliation Services,41.874005,-87.663518,POINT (-87.6635175498 41.874005383),41.878866,-87.625192,POINT (-87.6251921424 41.8788655841),1,4,2020,2,14,00:15:00,0,15,1,4,2020,2,14,00:15:00,0,15
9,2020-04-01 00:15:00,2020-04-01 00:15:00,240.0,1.30,NaN,NaN,11.0,10.0,6.25,0.00,0.0,0.0,6.25,Credit Card,Star North Management LLC,41.978830,-87.771167,POINT (-87.771166703 41.9788295262),41.985015,-87.804532,POINT (-87.8045320063 41.9850151008),1,4,2020,2,14,00:15:00,0,15,1,4,2020,2,14,00:15:00,0,15
10,2020-04-01 00:15:00,2020-04-01 00:30:00,552.0,1.02,NaN,NaN,14.0,NaN,7.50,0.00,0.0,1.0,8.50,Cash,Flash Cab,41.968069,-87.721559,POINT (-87.7215590627 41.968069),NaN,NaN,NaN,1,4,2020,2,14,00:15:00,0,15,1,4,2020,2,14,00:30:00,0,30
11,2020-04-01 00:15:00,2020-04-01 00:15:00,240.0,0.60,NaN,NaN,77.0,77.0,5.00,1.00,0.0,0.0,6.00,Credit Card,Taxi Affiliation Services,41.986712,-87.663416,POINT (-87.6634164054 41.9867117999),41.986712,-87.663416,POINT (-87.6634164054 41.9867117999),1,4,2020,2,14,00:15:00,0,15,1,4,2020,2,14,00:15:00,0,15
12,2020-04-01 00:15:00,2020-04-01 00:15:00,240.0,0.90,NaN,NaN,16.0,16.0,5.50,0.00,0.0,0.0,5.50,Cash,Taxi Affiliation Services,41.953582,-87.723452,POINT (-87.7234523905 41.9535821253),41.953582,-87.723452,POINT (-87.7234523905 41.9535821253),1,4,2020,2,14,00:15:00,0,15,1,4,2020,2,14,00:15:00,0,15
13,2020-04-01 00:15:00,2020-04-01 00:15:00,43.0,0.04,NaN,NaN,14.0,14.0,3.25,0.00,0.0,0.0,3.25,Cash,Flash Cab,41.968069,-87.721559,POINT (-87.7215590627 41.968069),41.968069,-87.721559,POINT (-87.7215590627 41.968069),1,4,2020,2,14,00:15:00,0,15,1,4,2020,2,14,00:15:00,0,15
14,2020-04-01 00:15:00,2020-04-01 00:30:00,1339.0,3.97,NaN,NaN,43.0,41.0,15.00,0.00,0.0,0.0,15.00,Cash,Flash Cab,41.761578,-87.572782,POINT (-87.5727819867 41.7615779081),41.794090,-87.592311,POINT (-87.592310855 41.794090253),1,4,2020,2,14,00:15:00,0,15,1,4,2020,2,14,00:30:00,0,30
15,2020-04-01 00:15:00,2020-04-01 00:30:00,955.0,4.10,NaN,NaN,8.0,24.0,13.75,0.00,0.0,0.0,13.75,Cash,Chicago Carriage Cab Corp,41.899602,-87.633308,POINT (-87.6333080367 41.899602111),41.901207,-87.676356,POINT (-87.6763559892 41.9012069941),1,4,2020,2,14,00:15:00,0,15,1,4,2020,2,14,00:30:00,0,30
16,2020-04-01 00:30:00,2020-04-01 00:30:00,60.0,0.00,NaN,NaN,2.0,2.0,3.25,0.00,0.0,0.0,3.25,Cash,Taxi Affiliation Services,42.001571,-87.695013,POINT (-87.6950125892 42.001571027),42.001571,-87.695013,POINT (-87.6950125892 42.001571027),1,4,2020,2,14,00:30:00,0,30,1,4,2020,2,14,00:30:00,0,30
17,2020-04-01 00:30:00,2020-04-01 00:45:00,315.0,1.74,NaN,NaN,14.0,NaN,7.50,0.00,0.0,0.0,7.50,Cash,Flash Cab,41.968069,-87.721559,POINT (-87.7215590627 41.968069),NaN,NaN,NaN,1,4,2020,2,14,00:30:00,0,30,1,4,2020,2,14,00:45:00,0,45
18,2020-04-01 00:30:00,2020-04-01 00:45:00,1279.0,12.35,NaN,NaN,28.0,43.0,32.25,0.00,0.0,0.0,32.25,Prcard,Flash Cab,41.874005,-87.663518,POINT (-87.6635175498 41.874005383),41.761578,-87.572782,POINT (-87.5727819867 41.7615779081),1,4,2020,2,14,00:30:00,0,30,1,4,2020,2,14,00:45:00,0,45
19,2020-04-01 00:30:00,2020-04-01 01:00:00,2220.0,0.30,NaN,NaN,8.0,8.0,22.25,0.00,0.0,0.0,22.25,Unknown,Taxi Affiliation Services,41.899602,-87.633308,POINT (-87.6333080367 41.899602111),41.899602,-87.633308,POINT (-87.6333080367 41.899602111),1,4,2020,2,14,00:30:00,0,30,1,4,2020,2,14,01:00:00,1,0
20,2020-04-01 00:30:00,2020-04-01 00:30:00,48.0,0.00,NaN,NaN,41.0,41.0,3.25,0.00,0.0,0.0,3.25,Cash,Flash Cab,41.794090,-87.592311,POINT (-87.592310855 41.794090253),41.794090,-87.592311,POINT (-87.592310855 41.794090253),1,4,2020,2,14,00:30:00,0,30,1,4,2020,2,14,00:30:00,0,30
21,2020-04-01 00:30:00,2020-04-01 00:30:00,47.0,0.03,NaN,NaN,14.0,14.0,3.25,0.00,0.0,0.0,3.25,Cash,Flash Cab,41.968069,-87.721559,POINT (-87.7215590627 41.968069),41.968069,-87.721559,POINT (-87.7215590627 41.968069),1,4,2020,2,14,00:30:00,0,30,1,4,2020,2,14,00:30:00,0,30
22,2020-04-01 00:30:00,2020-04-01 00:45:00,840.0,7.80,NaN,NaN,32.0,25.0,21.50,0.00,0.0,0.0,21.50,Cash,Taxi Affiliation Services,41.878866,-87.625192,POINT (-87.6251921424 41.8788655841),41.890609,-87.756047,POINT (-87.7560467111 41.8906088526),1,4,2020,2,14,00:30:00,0,30,1,4,2020,2,14,00:45:00,0,45
23,2020-04-01 00:30:00,2020-04-01 00:45:00,840.0,0.00,NaN,NaN,8.0,68.0,3.25,0.00,0.0,0.0,3.25,Cash,Blue Ribbon Taxi Association Inc.,41.899602,-87.633308,POINT (-87.6333080367 41.899602111),41.777196,-87.642498,POINT (-87.6424975271 41.7771962546),1,4,2020,2,14,00:30:00,0,30,1,4,2020,2,14,00:45:00,0,45
24,2020-04-01 00:30:00,2020-04-01 00:30:00,658.0,5.95,NaN,NaN,7.0,77.0,17.00,1.25,0.0,0.0,18.75,Credit Card,Flash Cab,41.922686,-87.649489,POINT (-87.6494887289 41.9226862843),41.986712,-87.663416,POINT (-87.6634164054 41.9867117999),1,4,2020,2,14,00:30:00,0,30,1,4,2020,2,14,00:30:00,0,30
25,2020-04-01 00:30:00,2020-04-01 00:30:00,660.0,0.00,NaN,NaN,2.0,3.0,12.25,2.00,0.0,0.0,14.25,Credit Card,Taxi Affiliation Services,42.001571,-87.695013,POINT (-87.6950125892 42.001571027),41.965812,-87.655879,POINT (-87.6558787862 41.96581197),1,4,2020,2,14,00:30:00,0,30,1,4,2020,2,14,00:30:00,0,30
26,2020-04-01 00:30:00,2020-04-01 01:15:00,2160.0,0.00,NaN,NaN,28.0,42.0,31.25,0.00,0.0,0.0,31.25,Cash,Taxi Affiliation Services,41.874005,-87.663518,POINT (-87.6635175498 41.874005383),41.778877,-87.594925,POINT (-87.5949254391 41.7788768603),1,4,2020,2,14,00:30:00,0,30,1,4,2020,2,14,01:15:00,1,15
27,2020-04-01 00:45:00,2020-04-01 01:00:00,1686.0,8.62,NaN,NaN,41.0,44.0,25.75,0.00,0.0,0.0,25.75,Prcard,Flash Cab,41.794090,-87.592311,POINT (-87.592310855 41.794090253),41.740206,-87.615970,POINT (-87.6159695226 41.7402057565),1,4,2020,2,14,00:45:00,0,45,1,4,2020,2,14,01:00:00,1,0
28,2020-04-01 00:45:00,2020-04-01 00:45:00,185.0,0.51,NaN,NaN,2.0,2.0,4.50,0.00,0.0,0.0,4.50,Cash,Flash Cab,42.001571,-87.695013,POINT (-87.6950125892 42.001571027),42.001571,-87.695013,POINT (-87.6950125892 42.001571027),1,4,2020,2,14,00:45:00,0,45,1,4,2020,2,14,00:45:00,0,45
29,2020-04-01 00:45:00,2020-04-01 00:45:00,360.0,1.00,NaN,NaN,16.0,16.0,6.50,0.00,0.0,0.0,6.50,Cash,Taxi Affiliation Services,41.953582,-87.723452,POINT (-87.7234523905 41.9535821253),41.953582,-87.723452,POINT (-87.7234523905 41.9535821253),1,4,2020,2,14,00:45:00,0,45,1,4,2020,2,14,00:45:00,0,45
30,2020-04-01 00:45:00,2020-04-01 01:00:00,960.0,5.40,NaN,NaN,11.0,3.0,16.50,0.00,0.0,1.0,17.50,Cash,Star North Management LLC,41.978830,-87.771167,POINT (-87.771166703 41.9788295262),41.965812,-87.655879,POINT (-87.6558787862 41.96581197),1,4,2020,2,14,00:45:00,0,45,1,4,2020,2,14,01:00:00,1,0
31,2020-04-01 00:45:00,2020-04-01 00:45:00,120.0,0.50,NaN,NaN,77.0,77.0,4.25,3.00,0.0,0.0,7.25,Credit Card,Taxi Affiliation Services,41.986712,-87.663416,POINT (-87.6634164054 41.9867117999),41.986712,-87.663416,POINT (-87.6634164054 41.9867117999),1,4,2020,2,14,00:45:00,0,45,1,4,2020,2,14,00:45:00,0,45
32,2020-04-01 00:45:00,2020-04-01 00:45:00,360.0,2.60,NaN,NaN,76.0,76.0,9.25,0.00,0.0,4.0,13.25,Cash,KOAM Taxi Association,41.980264,-87.913625,POINT (-87.913624596 41.9802643146),41.980264,-87.913625,POINT (-87.913624596 41.9802643146),1,4,2020,2,14,00:45:00,0,45,1,4,2020,2,14,00:45:00,0,45
33,2020-04-01 00:45:00,2020-04-01 01:00:00,446.0,2.04,NaN,NaN,14.0,NaN,8.25,0.00,0.0,0.0,8.25,Cash,Flash Cab,41.968069,-87.721559,POINT (-87.7215590627 41.968069),NaN,NaN,NaN,1,4,2020,2,14,00:45:00,0,45,1,4,2020,2,14,01:00:00,1,0
34,2020-04-01 00:45:00,2020-04-01 00:45:00,60.0,0.00,NaN,NaN,2.0,2.0,90.00,9.50,0.0,0.0,99.50,Credit Card,Taxi Affiliation Services,42.001571,-87.695013,POINT (-87.6950125892 42.001571027),42.001571,-87.695013,POINT (-87.6950125892 42.001571027),1,4,2020,2,14,00:45:00,0,45,1,4,2020,2,14,00:45:00,0,45
35,2020-04-01 00:45:00,2020-04-01 00:45:00,44.0,0.04,NaN,NaN,14.0,14.0,3.25,0.00,0.0,0.0,3.25,Cash,Flash Cab,41.968069,-87.721559,POINT (-87.7215590627 41.968069),41.968069,-87.721559,POINT (-87.7215590627 41.968069),1,4,2020,2,14,00:45:00,0,45,1,4,2020,2,14,00:45:00,0,45
36,2020-04-01 01:00:00,2020-04-01 01:15:00,1483.0,12.16,NaN,NaN,32.0,1.0,32.50,0.00,0.0,0.0,32.50,Prcard,Flash Cab,41.878866,-87.625192,POINT (-87.6251921424 41.8788655841),42.009623,-87.670167,POINT (-87.6701668569 42.0096228806),1,4,2020,2,14,01:00:00,1,0,1,4,2020,2,14,01:15:00,1,15
37,2020-04-01 01:00:00,2020-04-01 01:15:00,660.0,0.20,NaN,NaN,67.0,71.0,11.50,0.00,0.0,0.0,11.50,Cash,Taxi Affiliation Services,41.775929,-87.666596,POINT (-87.6665962653 41.7759288274),41.744205,-87.656306,POINT (-87.6563059862 41.7442051463),1,4,2020,2,14,01:00:00,1,0,1,4,2020,2,14,01:15:00,1,15
38,2020-04-01 01:00:00,2020-04-01 01:15:00,780.0,2.50,NaN,NaN,1.0,1.0,10.50,0.00,0.0,1.0,11.50,Cash,Medallion Leasin,42.009623,-87.670167,POINT (-87.6701668569 42.0096228806),42.009623,-87.670167,POINT (-87.6701668569 42.0096228806),1,4,2020,2,14,01:00:00,1,0,1,4,2020,2,14,01:15:00,1,15
39,2020-04-01 01:00:00,2020-04-01 01:00:00,0.0,0.00,NaN,NaN,2.0,2.0,84.50,15.00,0.0,0.0,99.50,Credit Card,Taxi Affiliation Services,42.001571,-87.695013,POINT (-87.6950125892 42.001571027),42.001571,-87.695013,POINT (-87.6950125892 42.001571027),1,4,2020,2,14,01:00:00,1,0,1,4,2020,2,14,01:00:00,1,0
40,2020-04-01 01:00:00,2020-04-01 01:00:00,60.0,0.00,NaN,NaN,24.0,24.0,3.25,0.00,0.0,0.0,3.25,Cash,Taxi Affiliation Services,41.901207,-87.676356,POINT (-87.6763559892 41.9012069941),41.901207,-87.676356,POINT (-87.6763559892 41.9012069941),1,4,2020,2,14,01:00:00,1,0,1,4,2020,2,14,01:00:00,1,0
41,2020-04-01 01:00:00,2020-04-01 01:15:00,600.0,3.20,NaN,NaN,77.0,3.0,11.00,0.00,0.0,0.0,11.00,Cash,Taxi Affiliation Services,41.986712,-87.663416,POINT (-87.6634164054 41.9867117999),41.965812,-87.655879,POINT (-87.6558787862 41.96581197),1,4,2020,2,14,01:00:00,1,0,1,4,2020,2,14,01:15:00,1,15
42,2020-04-01 01:00:00,2020-04-01 01:15:00,807.0,0.43,NaN,NaN,77.0,77.0,7.75,0.00,0.0,1.5,9.25,Cash,Flash Cab,41.986712,-87.663416,POINT (-87.6634164054 41.9867117999),41.986712,-87.663416,POINT (-87.6634164054 41.9867117999),1,4,2020,2,14,01:00:00,1,0,1,4,2020,2,14,01:15:00,1,15
43,2020-04-01 01:00:00,2020-04-01 01:00:00,480.0,2.20,NaN,NaN,28.0,28.0,9.00,0.00,0.0,0.0,9.00,Cash,Taxi Affiliation Services,41.874005,-87.663518,POINT (-87.6635175498 41.874005383),41.874005,-87.663518,POINT (-87.6635175498 41.874005383),1,4,2020,2,14,01:00:00,1,0,1,4,2020,2,14,01:00:00,1,0
44,2020-04-01 01:00:00,2020-04-01 01:15:00,420.0,2.21,NaN,NaN,33.0,32.0,8.75,2.00,0.0,0.0,11.25,Credit Card,Flash Cab,41.857184,-87.620335,POINT (-87.6203346241 41.8571838585),41.878866,-87.625192,POINT (-87.6251921424 41.8788655841),1,4,2020,2,14,01:00:00,1,0,1,4,2020,2,14,01:15:00,1,15
45,2020-04-01 01:00:00,2020-04-01 01:00:00,0.0,0.00,NaN,NaN,11.0,11.0,3.25,0.00,0.0,0.0,3.25,Cash,Star North Management LLC,41.978830,-87.771167,POINT (-87.771166703 41.9788295262),41.978830,-87.771167,POINT (-87.771166703 41.9788295262),1,4,2020,2,14,01:00:00,1,0,1,4,2020,2,14,01:00:00,1,0
46,2020-04-01 01:15:00,2020-04-01 02:15:00,3926.0,26.16,NaN,NaN,76.0,76.0,69.25,0.00,0.0,0.0,69.25,Cash,Sun Taxi,41.980264,-87.913625,POINT (-87.913624596 41.9802643146),41.980264,-87.913625,POINT (-87.913624596 41.9802643146),1,4,2020,2,14,01:15:00,1,15,1,4,2020,2,14,02:15:00,2,15
47,2020-04-01 01:15:00,2020-04-01 01:30:00,47.0,0.06,NaN,NaN,16.0,16.0,3.25,0.00,0.0,0.0,3.25,Cash,Flash Cab,41.953582,-87.723452,POINT (-87.7234523905 41.9535821253),41.953582,-87.723452,POINT (-87.7234523905 41.9535821253),1,4,2020,2,14,01:15:00,1,15,1,4,2020,2,14,01:30:00,1,30
48,2020-04-01 01:15:00,2020-04-01 01:15:00,0.0,0.00,NaN,NaN,8.0,8.0,3.25,0.00,0.0,0.0,3.25,Cash,Taxi Affiliation Services,41.899602,-87.633308,POINT (-87.6333080367 41.899602111),41.899602,-87.633308,POINT (-87.6333080367 41.899602111),1,4,2020,2,14,01:15:00,1,15,1,4,2020,2,14,01:15:00,1,15
49,2020-04-01 01:30:00,2020-04-01 01:30:00,538.0,2.97,NaN,NaN,6.0,77.0,10.00,2.00,0.0,0.0,12.50,Credit Card,Chicago Carriage Cab Corp,41.944227,-87.655998,POINT (-87.6559981815 41.9442266014),41.986712,-87.663416,POINT (-87.6634164054 41.9867117999),1,4,2020,2,14,01:30:00,1,30,1,4,2020,2,14,01:30:00,1,30

### Analyze NULL values

In [271]:
dfc.isnull().sum()

TripStart                          0
TripEnd                            0
Trip Seconds                     139
Trip Miles                         1
Pickup Census Tract           219133
Dropoff Census Tract          219554
Pickup Community Area          16987
Dropoff Community Area         22333
Fare                              11
Tips                              11
Tolls                             11
Extras                            11
Trip Total                        11
Payment Type                       0
Company                            0
Pickup Centroid Latitude       16975
Pickup Centroid Longitude      16975
Pickup Centroid Location       16975
Dropoff Centroid Latitude      22298
Dropoff Centroid Longitude     22298
Dropoff Centroid  Location     22298
TripStart_dayofmonth               0
TripStart_month                    0
TripStart_year                     0
TripStart_dayofweek                0
TripStart_week                     0
TripStart_time                     0
TripStart_hourofday                0
TripStart_minuteofday              0
TripEnd_dayofmonth                 0
TripEnd_month                      0
TripEnd_year                       0
TripEnd_dayofweek                  0
TripEnd_week                       0
TripEnd_time                       0
TripEnd_hourofday                  0
TripEnd_minuteofday                0
dtype: int64